/** The thirty collectible specimens. IDs are stable save-data keys. */
export const PLANTS = [
  { id: 'solara-minima', name: 'Solara minima', rarity: 'common', description: 'A pocket-sized sun that opens one petal for every small victory.', trait: 'Little sunflowers' },
  { id: 'lunaria-rotunda', name: 'Lunaria rotunda', rarity: 'common', description: 'Round, coin-like leaves quietly collect the light of good ideas.', trait: 'Moon-coin leaves' },
  { id: 'spicula-pompom', name: 'Spicula pompom', rarity: 'common', description: 'A wonderfully awkward cactus with a very soft spot for persistence.', trait: 'Rosy cactus crown' },
  { id: 'campana-somnia', name: 'Campana somnia', rarity: 'uncommon', description: 'Its sleepy bells ring so softly that only daydreamers can hear them.', trait: 'Hanging dream bells' },
  { id: 'spiralis-curiosa', name: 'Spiralis curiosa', rarity: 'uncommon', description: 'A curious fern that turns every new question into another little curl.', trait: 'Unfurling spiral fronds' },
  { id: 'fungia-lumilux', name: 'Fungia lumilux', rarity: 'uncommon', description: 'A tiny forest of lantern caps, glowing brightest after a breakthrough.', trait: 'Glowing lantern caps' },
  { id: 'crystalia-lucens', name: 'Crystalia lucens', rarity: 'rare', description: 'Translucent leaves grow into a crystal compass pointing toward possibility.', trait: 'Faceted crystal rosette' },
  { id: 'plumaria-fanfara', name: 'Plumaria fanfara', rarity: 'rare', description: 'A proud fan of feathery fronds that celebrates every hard-won insight.', trait: 'Feather-fan canopy' },
  { id: 'nebula-pendula', name: 'Nebula pendula', rarity: 'epic', description: 'This starlit willow wears tiny moons at the ends of its wandering branches.', trait: 'Weeping lunar branches' },
  { id: 'aurelia-infinitum', name: 'Aurelia infinitum', rarity: 'exotic', description: 'A golden lotus said to bloom wherever curiosity refuses to stop growing.', trait: 'Celestial lotus bloom' },
  { id: 'trifolia-dulcis', name: 'Trifolia dulcis', rarity: 'common', description: 'A cheerful cluster of three-fold leaves with a taste for morning light.', trait: 'Three-fold clover crowns' },
  { id: 'rosula-tessella', name: 'Rosula tessella', rarity: 'common', description: 'Soft little tiles nest together in a perfectly patient rosette.', trait: 'Layered succulent tiles' },
  { id: 'gramina-pennata', name: 'Gramina pennata', rarity: 'common', description: 'Its golden grain nods along to thoughts that are still taking shape.', trait: 'Golden feather grass' },
  { id: 'fragaria-rubella', name: 'Fragaria rubella', rarity: 'common', description: 'Tiny ruby fruits hide beneath broad leaves until the time is right.', trait: 'Ruby teardrop berries' },
  { id: 'corallina-ramula', name: 'Corallina ramula', rarity: 'common', description: 'A land-loving coral that sends plump little branches in every direction.', trait: 'Coral finger branches' },
  { id: 'digitella-veluta', name: 'Digitella veluta', rarity: 'uncommon', description: 'Velvet cups climb a slender tower, each holding a drop of quiet wonder.', trait: 'Velvet cup spires' },
  { id: 'corda-volubilis', name: 'Corda volubilis', rarity: 'uncommon', description: 'Heart-shaped leaves follow a looping vine back to where they began.', trait: 'Heart-leaf arch' },
  { id: 'umbrella-viridula', name: 'Umbrella viridula', rarity: 'uncommon', description: 'A miniature canopy that would keep a very small explorer dry.', trait: 'Radial parasol leaves' },
  { id: 'tessera-serpentina', name: 'Tessera serpentina', rarity: 'uncommon', description: 'Tall, patterned blades stand watch over the rest of the garden.', trait: 'Zigzag ribbon blades' },
  { id: 'vespera-flabella', name: 'Vespera flabella', rarity: 'uncommon', description: 'Pleated fans turn amber when a new idea finally settles into place.', trait: 'Amber fan leaves' },
  { id: 'baccara-vitrea', name: 'Baccara vitrea', rarity: 'rare', description: 'Its translucent berries gather little reflections of the world around them.', trait: 'Glass-bead berry tree' },
  { id: 'cuculla-aurantia', name: 'Cuculla aurantia', rarity: 'rare', description: 'Curious copper pitchers save the last warm drops of the afternoon.', trait: 'Copper pitcher cups' },
  { id: 'rosaria-vesicula', name: 'Rosaria vesicula', rarity: 'rare', description: 'Round blossoms unfurl in a spiral, as if each were a tiny folded cloud.', trait: 'Spiral cloud blossoms' },
  { id: 'arbor-spiravita', name: 'Arbor spiravita', rarity: 'rare', description: 'An old soul in a small pot, growing a new bend for every season.', trait: 'Twisted miniature tree' },
  { id: 'draconia-rubrivena', name: 'Draconia rubrivena', rarity: 'epic', description: 'Winged leaves shelter a scarlet bloom with the confidence of a sleeping dragon.', trait: 'Dragon wings and flame' },
  { id: 'astrantia-radiata', name: 'Astrantia radiata', rarity: 'epic', description: 'A star-shaped flower traces delicate constellations in the evening air.', trait: 'Constellation starburst' },
  { id: 'velaria-caerulea', name: 'Velaria caerulea', rarity: 'epic', description: 'Blue lanterns trail silk-like tendrils that drift without a breeze.', trait: 'Floating silk lanterns' },
  { id: 'chronoflora-annularis', name: 'Chronoflora annularis', rarity: 'exotic', description: 'Silver rings bloom around an amber heart, turning at their own impossible pace.', trait: 'Nested orbital blossom' },
  { id: 'noctiluca-geminata', name: 'Noctiluca geminata', rarity: 'exotic', description: 'Twin orchids trade moonlight between their dark and luminous petals.', trait: 'Twin eclipse orchids' },
  { id: 'palatia-prismatica', name: 'Palatia prismatica', rarity: 'exotic', description: 'Opaline terraces hover above a stem too delicate to hold them.', trait: 'Floating opal terraces' },
];
